[default]
coordinates_path = "sea_demo/data/routes/city_coordinates.json"
summary_path = "sea_demo/data/routes/routes_summary.json"
routes_path = "sea_demo/data/routes/"
gpd_url = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson"
cities = [
    "Vienna",
    "Graz",
    "Linz",
    "Salzburg",
    "Innsbruck",
    "Klagenfurt",
    "St. Pölten",
    "Eisenstadt",
    "Bregenz",
    "Lienz",
]